# 每行格式为 文件名 URL
# 仅保留 Bandix 运行和 LuCI 中文界面所需 IPK
luci-app-bandix-plus_0.1.2-r2_all.ipk https://github.com/timsaya/luci-app-bandix-plus/releases/download/v0.1.2-r2/luci-app-bandix-plus_0.1.2-r2_all.ipk
luci-i18n-bandix-plus-zh-cn_26.171.64752.8957a06_all.ipk https://github.com/timsaya/luci-app-bandix-plus/releases/download/v0.1.2-r2/luci-i18n-bandix-plus-zh-cn_26.171.64752.8957a06_all.ipk
bandix-plus_0.1.1-r2_x86_64.ipk https://github.com/timsaya/openwrt-bandix-plus/releases/download/v0.1.1-r2/bandix-plus_0.1.1-r2_x86_64.ipk
