# 每行一个包定义：<feed_name> <output_filename> <url>
# 说明：
# - feed_name 用于生成 src/gz 源名，可复用同一个 feed 名
# - output_filename 为下载后保存到 feed/<feed_name>/ 下的文件名
# - url 为可直接下载的 .ipk/.apk 地址

local_bandix luci-app-bandix-plus_0.1.2-r2_all.ipk https://github.com/timsaya/luci-app-bandix-plus/releases/download/v0.1.2-r2/luci-app-bandix-plus_0.1.2-r2_all.ipk
local_bandix luci-i18n-bandix-plus-zh-cn_26.171.64752.8957a06_all.ipk https://github.com/timsaya/luci-app-bandix-plus/releases/download/v0.1.2-r2/luci-i18n-bandix-plus-zh-cn_26.171.64752.8957a06_all.ipk
local_bandix bandix-plus_0.1.1-r2_x86_64.ipk https://github.com/timsaya/openwrt-bandix-plus/releases/download/v0.1.1-r2/bandix-plus_0.1.1-r2_x86_64.ipk
